---
- name: Ensure openshift-install {{ openshift_version }} binary exists - Linux
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}/openshift-install-linux.tar.gz
    dest: /tmp/openshift-install-linux-{{ openshift_version }}.tar.gz
    mode: '0440'

- name: Extract openshift-install to /tmp/ - Linux
  unarchive:
    src: /tmp/openshift-install-linux-{{ openshift_version }}.tar.gz
    dest: /tmp/
