---
- name: Ensure openshift-install {{ openshift_version }} binary exists - MacOSX
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}/openshift-install-mac.tar.gz
    dest: /tmp/openshift-install-mac-{{ openshift_version }}.tar.gz
    mode: '0440'

- name: Extract openshift-install to /tmp/ - MacOSX
  unarchive:
    src: /tmp/openshift-install-mac-{{ openshift_version }}.tar.gz
    dest: /tmp/
